### ISSUE TITLE
2 Problem, Proxy + Captcha

### ISSUE THREAD

**Issue by ki03pm** [Sysys242/DMDPY#3]
Proxy :
if the proxy dies while running, or dies when it wants to run, the software will continue to run without stopping, and there is no error handling for that, for example like max retries when getting the proxy error

Captcha - Join Server : 
there are no max retries to join the server, when I get a captcha, I have experienced it, it continues to get captcha up to 80 times and it doesn't stop automatically,, need like retry on cap

*And Maybe you can edit the user agent ,etc  to a newer one

**Comment by Sysys242** [comment]
- Edit the useragent: useless
- Proxy handling: ik it will just print error,  user will have to close, it's a simple project, not fully profesional that i sell or idk 
- Captcha: you should put a valid captcha or just don't solve, it have handler for non solving so use it :)
